### PR TITLE
Chunk height gt1000

### PR DESCRIPTION
**Pull request by helfi92**
Problem: `newlineCount` increments when it sees \n, but not every line ends with \n.
Solution: Increment `newlineCount` when it sees \r, because every line either ends with \r\n or simply \r.

Other changes:
-  Since new lines don't always end with \n, I changed `NORMALIZE_NEWLINES` to `/\r+[\n]?/gm`

This solves the issue we were having with the following [log](http://localhost:4000/?url=https%3A%2F%2Fpublic-artifacts.taskcluster.net%2F5qB6Zqc0Tw2_wkKwHgGNGQ%2F0%2Fpublic%2Flogs%2Flive_backing.log&highlightStart=&highlightEnd=&lineNumber=1445&wrapLines=false&showLineNumbers=true&jumpToHighlight=false) at line number 1446: 
It was counting from 1001 instead of proceeding with 1447.

### CODE REVIEW

**Comment by helfi92** [comment]
@eliperelman Ready for review when you have the time

**Comment by eliperelman** [comment]
@helfi92 are we sure that every line ends with `\r` or `\r\n`? Do some lines only end in `\n`?

**Review by eliperelman — CHANGES_REQUESTED** [review]
So in testing this locally, I still noticed some discrepancies in the way that line numbers were being generated, along with a large gap at the bottom of the page. I did a bit of debugging and made the following changes to help:

``` js
// Switch the NORMALIZE_NEWLINES regex to this:
// The regex was looking for multiple newlines
// when really I think we only want to match one at a time
const NORMALIZE_NEWLINES = /\r[\n]?/gm;

// Add back ENCODED_NEWLINE
const ENCODED_NEWLINE = 10;

// Change when we increment newlineCount to:
const isNewline = buffer[index] === ENCODED_CARRIAGERETURN ||
  (buffer[index] === ENCODED_NEWLINE &&
    buffer[index - 1] !== ENCODED_CARRIAGERETURN);

if (isNewline) {
  newlineCount++;
}
```

I think that would fix the remaining issues. Could you try that out and see what you think?

**Comment by eliperelman** [comment]
So one thing about my review, it's only relevant if all new lines contain `\r` or `\n`. If they always contain `\r`, which I'm inclined to think isn't true, then most of what I wrote isn't needed. Also if it's either `\r` or `\n`, then the regex should probably be switched to reflect that the `\r` isn't required like it currently is.

**Comment by helfi92** [comment]
That's right. If you use any URL online, then it will probably have cases without \r, but the environment that Mozilla uses to build jobs is probably running on Windows (from what I can see), where new lines are denoted as \r\n. But I guess we want to support all general cases. So yeah, I agree with you and I think your suggestions are the way to go.

**Review by eliperelman — APPROVED** [review]

**Pull request merged**
