### PR TITLE
Setting and functionality to follow a log by keeping scrolled to the bottom

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by eliperelman** [comment]
@gregarndt @helfi92 would either of you two mind taking a look at this to see if this works as intended?

``` sh
npm start
open http://localhost:4000/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2F3cP0YDWhSiKx4sj10PwUsQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```

**Comment by helfi92** [comment]
@eliperelman 2 things I noticed:
1- When you set the radio button Follow Log then start scrolling, it checks it off. Is that intended?
2- When I run it on this huge [log](https://queue.taskcluster.net/v1/task/B8yyH1HORxKkQ9p1Sh0CFA/runs/0/artifacts/public%2Flogs%2Flive_backing.log), it seems to have no end. I can always scroll down, even if follow log is checked.

**Comment by helfi92** [comment]
Tried it on another connection and I can't seem to reproduce the second issue I mentioned anymore. Ok will look at code now.

**Comment by eliperelman** [comment]
@helfi92 good to know. And yes, that is the intention; scrolling disables following the log.

**Comment by helfi92** [comment]
@eliperelman  Code looks good & pretty 👍 If users set Follow Log then scroll, it sets Follow Log to false. This becomes annoying to the developer when he/she refreshes the page because it wouldn't scroll him down to the bottom. Thoughts?

**Comment by eliperelman** [comment]
"Follow Log" is persisted based on the log being rendered. For instance in tools we could render logs with `followLog=true`, then a refresh would automatically move them to the bottom and follow. Or we could turn it on for live logs only. So the persistence of the live log is based on the URL generation, or the last known URL state. Either way, these are intended.

**Comment by helfi92** [comment]
@eliperelman I see. If that's the case, then it's definitely working as intended

**Pull request merged**
